# Generated by Django 3.0.4 on 2020-03-24 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200324_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryout',
            name='admin',
            field=models.ForeignKey(default='b3saleh', on_delete=django.db.models.deletion.CASCADE, related_name='my_tryouts', to='hello.user'),
            preserve_default=False,
        ),
    ]
