# Generated by Django 3.0.4 on 2020-03-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_tryout_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tryout',
            name='admin',
        ),
    ]
