# Generated by Django 3.0.4 on 2020-03-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_tryout_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='playerID',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='criterion',
            old_name='criteriaName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='criterion',
            old_name='tryoutID',
            new_name='tryout',
        ),
        migrations.RenameField(
            model_name='evalution',
            old_name='criterionID',
            new_name='criterion',
        ),
        migrations.RenameField(
            model_name='evalution',
            old_name='playerID',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='tryoutID',
            new_name='tryout',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='tryoutID',
            new_name='tryout',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tryoutID',
            new_name='tryout',
        ),
    ]
