# Generated by Django 3.0.4 on 2020-03-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20200324_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryout',
            name='executives',
            field=models.ManyToManyField(to='hello.user'),
        ),
        migrations.AlterField(
            model_name='tryout',
            name='admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='my_tryouts', to='hello.user'),
        ),
    ]
